#name: Build
#on: [ push, pull_request ]
#jobs:
#  build-common:
#    name: Build Common
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v2
#
#      - name: set up JDK
#        uses: actions/setup-java@v1
#        with:
#          java-version: 11
#
#      - name: Assemble
#        run: ./gradlew common:build
#
#  build-web:
#    needs: build-common
#    name: Build Web
#    runs-on: ubuntu-latest
#    steps:
#      - name: Setup Java
#        uses: actions/setup-java@v1
#        with:
#          java-version: 11
#
#      - name: Fetch Sources
#        uses: actions/checkout@v2
#
#      - name: Test and Build
#        run: ./gradlew web:build
#
#  build-android:
#    needs: build-common
#    name: Build Android
#    runs-on: ubuntu-latest
#    steps:
#      - name: Setup Java
#        uses: actions/setup-java@v1
#        with:
#          java-version: 11
#
#      - name: Fetch Sources
#        uses: actions/checkout@v2
#
#      - name: Test and Build
#        run: ./gradlew android:assemble