name: Publish Web
on: [workflow_dispatch]
jobs:
  publish:
    name: Build Web
    runs-on: ubuntu-latest
    steps:
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Fetch Sources
        uses: actions/checkout@v2

      - name: Check Tag
        run: |
          git fetch --tags
          git describe --exact-match --tags HEAD

      - name: Save Tag Name
        id: tag
        run: echo "::set-output name=tag::$(git describe --exact-match --tags HEAD)"

      # Installing Kobweb with brew
      - name: Install Kobweb
        run: |
          wget https://github.com/varabyte/kobweb/releases/download/cli-v0.9.9/kobweb-0.9.9.zip
          unzip kobweb-0.9.9.zip
          echo "${GITHUB_WORKSPACE}/kobweb-0.9.9/bin" >> $GITHUB_PATH

      # Validate wrapper
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1.0.3

      # Build application
      - name: Build
        run: |
          cd kobweb
          kobweb version
          kobweb export --layout static --mode dumb

      # If main branch update, deploy to gh-pages
      - name: Publish
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: kobweb/build/site # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch
          CLEAN_EXCLUDE: "CNAME" # Automatically remove deleted files from the deploy branch
          COMMIT_MESSAGE: "Release ${{ steps.tag.outputs.tag }}"
